name: EmilyDrums
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e1e1e1'
    - '#e4ab27'
    - '#e6501b'
    - '#6d8696'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
