name: EmilyDrums
favicon: null
layout_spectrum: 0.21674
typography_spectrum: 0.71795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#271919'
    - '#5d4333'
    - '#8f716f'
    - '#e7d7cb'
  brandStrength: 1
  lightness: 0.5207903957925737
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
