name: EmilyDrums
favicon: null
layout_spectrum: 0.5607961493078619
typography_spectrum: 0.35408629989251494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#271919'
    - '#5d4333'
    - '#8f716f'
    - '#e7d7cb'
  brandStrength: 0.375
  lightness: 0.5207903957925737
  saturation: 0.3316530385054648
  rhythmicContrast: 0.38164274278096855
purpose: []
